### ISSUE TITLE
OSError: [Errno 30] Read-only file system: '/u'

### ISSUE THREAD

**Issue by wanglec** [XiangLi1999/PrefixTuning#27]
python train_e2e.py --optim_prefix yes --preseqlen 5 --epoch 5 --learning_rate 0.00005 --mode webnlg --bsz 5 --seed 101
would cause the error on my local PC below. I just did the environment set up and install nothing else. Should I install something instead?

Traceback (most recent call last):
  File "/Users/.../PrefixTuning/transformers/src/transformers/configuration_utils.py", line 355, in get_config_dict
    local_files_only=local_files_only,
  File "/Users/.../PrefixTuning/transformers/src/transformers/file_utils.py", line 719, in cached_path
    local_files_only=local_files_only,
  File "/Users/.../PrefixTuning/transformers/src/transformers/file_utils.py", line 821, in get_from_cache
    os.makedirs(cache_dir, exist_ok=True)
  File "/Users/.../opt/anaconda3/envs/sc/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Users/.../opt/anaconda3/envs/sc/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Users/.../opt/anaconda3/envs/sc/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 4 more times]
  File "/Users/.../opt/anaconda3/envs/sc/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/u'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_language_modeling.py", line 1159, in <module>
    main()
  File "run_language_modeling.py", line 546, in main
    config = AutoConfig.from_pretrained(model_args.model_name_or_path, cache_dir=model_args.cache_dir)
  File "/Users/.../PrefixTuning/transformers/src/transformers/configuration_auto.py", line 310, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/Users/.../PrefixTuning/transformers/src/transformers/configuration_utils.py", line 368, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 'gpt2-medium'. Make sure that:

- 'gpt2-medium' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'gpt2-medium' is the correct path to a directory containing a config.json file

**Comment by wanglec** [comment]
Ok I think I just need to change the cache_dir to my local address.
